import { Logout } from "@mui/icons-material";
import { Box, Button } from "@mui/material";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { signOut } from "next-auth/react";
const Dashboard: NextPage = () => {
  const { data } = useSession();
  console.log(data?.user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box display="flex" alignItems="center" gap={2}>
          Hello, {data?.user?.name}
          <Button
            endIcon={<Logout />}
            onClick={() => signOut({ callbackUrl: "/signin" })}
            color="error"
          >
            Logout
          </Button>
        </Box>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Dashboard Page</a>
        </h1>
      </main>
    </div>
  );
};

export default Dashboard;
